services:


  client:
    ports:
      - 3000:3000
    build:
      context: "./client"
      dockerfile: "Dockerfile"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

  
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamo/data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  
  sql-local:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/


  server:
    depends_on:
      - dynamodb-local
    ports:
      - 8080:8080
    build:
      context: "./server"
      dockerfile: "Dockerfile"
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
      - /usr/src/server/dist
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_KEY_SECRET}'  